# Generated by Django 4.0 on 2022-07-11 23:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_submitted',
            field=models.DateField(default=datetime.datetime(2022, 7, 11, 23, 13, 54, 349434)),
        ),
    ]
